name: Monitor Dropbox

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos
  workflow_dispatch:  # Permite ejecución manual

jobs:
  convert_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run converter
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: python pdf_converter.py
